version: "2"
services:
  webcat:
    image: tenforce/webcat:0.2.3
    links:
      - identifier:backend
    environment:
      VIRTUAL_HOST: "webcat.big-data-europe.aksw.org"
      VIRTUAL_PORT: "80"
    ports:
      - 89:80
    networks:
      - bdi
      - default
    labels:
      - "logging=true"
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
    volumes:
      - ./mu/config/dispatcher:/config
    labels:
      - "logging=true"
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    environment:
      VIRTUAL_HOST: "db.webcat.big-data-europe.aksw.org"
    volumes:
      - ./mu/data/db:/data
    labels:
      - "logging=true"
  resource:
    image: semtech/mu-cl-resources:1.10.1
    links:
      - db:database
    volumes:
      - ./mu/config/resources:/config
    environment:
      BOOT: mu-cl-resources
    labels:
      - "logging=true"
networks:
  bdi:
    external:
      name: appbdiide_default
